#ifndef MESSAGE_TYPE_H
#define MESSAGE_TYPE_H
#endif

enum MessageType {
    STOCK_DIRECTORY_MESSAGE = 'R',
    SYSTEM_EVENT_MESSAG = 'S',
    STOCK_TRADING_ACTION_MESSAGE = 'H',
    REG_SHO_SHORT_SALE_PRICE_TEST_RESTRICTED_INDICATOR = 'Y',
    MARKET_PARTICIPANT_POSITION_MESSAGE = 'L',
    MARKET_WIDE_CIRCUIT_BREAKER_DECLINE_LEVEL_MESSAGE = 'V',
    MARKET_WIDE_CIRCUIT_BREAKER_STATUS_MESSAGE = 'W',
    QUOTING_PERIOD_UPDATE = 'K',
    LULD_AUCTION_COLLAR = 'J',
    OPERATIONAL_HALT = 'h',
    ADD_ORDER_NO_MPID_ATTRIBUTION_MESSAGE = 'A',
    ADD_ORDER_MPID_ATTRIBUTION_MESSAGE = 'F',
    ADD_ORDER_ORDER_EXECUTED_MESSAGE = 'E',
    ADD_ORDER_ORDER_EXECUTED_WITH_PRICE_MESSAGE = 'C',
    ORDER_CANCEL_MESSAGE = 'X',
    ORDER_DELETE_MESSAGE = 'D',
    ORDER_REPLACE_MESSAGE = 'U',
    TRADE_MESSAGE = 'P',
    CROSS_TRADE_MESSAGE = 'Q',
    BROKEN_TRADE_MESSAGE = 'B',
    NOII_MESSAGE = 'I',
    RETAIL_INTEREST_MESSAGE = 'N',
    DIRECT_LISTING_WITH_CAPITAL_RAISE_MESSAGE = 'O',
};
